sudo: false
language: python
python:
  - pypy
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 2.7
notifications:
  email: false
stages:
  - test
  - lint
jobs:
  include:
    - stage: lint
      python: 3.6
      script: make lint

stage: test

script: make test

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install flake8==2.6.2; fi
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt || pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
after_success:
  codecov
